#include <iostream>
#include <stdlib.h>
#include "Item.h"

#ifndef __WEAPON_H_INCLUDED__
#define __WEAPON_H_INCLUDED__

class Weapon : Item
{
public:
	Weapon();
protected:
	//base information
	char *type;				//type of weapon: pole, sword, dagger, hammer/axe
	int forms;				//forms
	char **form;			//name of corresponding form
	int *hands;				//hands required to use corresponding form
	int *dice;				//number of damage die of corresponding form
	int *damage;			//damage die of corresponding form
	float *reach;			//reach of corresponding form
	int *coverage;			//a number representing the area that an attack from this weapon covers, directly affects dodge attempts

	//INFO ON CRITICAL HITS:
	//A CRITICAL HIT DOUBLES DICE
	//ROLLING A CRITICAL ALLOWS THE PLAYER TO ROLL ON THE CRITICAL TABLE FOR THAT SPECIFIC CHARACTER/MONSTER
	//THE CRITICAL TABLE RESULTS ARE DIRECTLY AFFECTED BY ARMOR WORN, HEALTH CONDITIONS, WEAPON/FORM BEING USED, AND ANY OTHER APPLICABLE FACTORS
	//SO IF WEARING A HELMET, DYING OF BEING HIT IN THE HEAD BY A SWORD IS INCREDIBLY UNLIKELY
	//WHILE IF WEARING A GAMBESON, BEING STABBED IN THE HEART OR LUNG AND DYING SHORTLY AFTER IS A STRONG POSSIBILITY

	//INFO ON DAMAGE AND BLEEDING:
	//A CRUSH ATTACK WILL RESULT IN 1 LEVELS OF BLEEDING
	//A STAB ATTACK WILL RESULT IN 2 LEVELS OF BLEEDING
	//A CUT ATTACK WILL RESULT IN 3 LEVELS OF BLEEDING
	//TAKING 6 DAMAGE OR MORE FROM AN ATTACK INFLICTS A LEVEL OF BLEEDING
	//ALL BLEEDING FROM CRUSH ATTACKS IS INTERNAL
	//BLEEDING HAS A CHANCE TO STOP ON ITS OWN. THIS CHANCE REDUCES WITH EACH LEVEL OF BLEEDING. AT 5 LEVELS OF BLEEDING, YOU'RE FUCKED WITHOUT TREATMENT
	//A LEVEL OF BLEEDING MEANS A LOSS OF 1 HEALTH PER 10 MINUTES
	//SO, 13 LEVELS OF BLEEDING MEANS A LOSS OF 1.3 HEALTH PER MINUTE
	//USUALLY, AFTER A FIGHT, YOU WILL NEED TO SEE A HEALER IF ANYONE GOT INJURED SIGNIFICANTLY
	//HEALERS CAN BE UNRELIABLE
	//HEALING MAGIC NEVER WORKS GOOD
	//ONE OF THE HEALING SPELLS JUST FORCES THE BLOOD TO CLOT IN THE AREA OF BLEEDING. THIS SOMETIMES LATER RESULTS IN AMPUTATION BUT IS QUICK AND EASY TO CAST
	//ONE OF THE OTHER HEALING SPELLS IS MORE OBVIOUSLY BLOOD MAGIC AND THEREFORE SCARY, BUT IS BASICALLY A BLOOD TRANSFUSION. KEEPS SOMEONE ALIVE FOR A BIT LONGER ASSUMING THEIR BODY DOESN'T REJECT THE TRANSFUSION
	//ONE HEALING GOO CAN BE FORCED INTO WOUNDS TO CLOSE THEM, ITS STERILE SO DON'T WORRY ABOUT IT, THOUGH IT MIGHT PERMANENTLY LOWER YOUR HEALTH
	//ONE HEALING DRINK BASICALLY IS JUST SUBSTITUTE BLOOD STUFF, BUT IT ONLY STAYS IN YOUR SYSTEM FOR A FEW DAYS SO ITS A TEMP HEALTH BOOSTER FOR BLEEDING RECOVERY
	//ONE HEALING GOO STERILIZES WOUNDS AND THATS IT, WOW

	//upgradeable stats
	int *speed;				//speed of corresponding form
	int *draw;				//draw speed of corresponding form, if applicable
	int *cut;				//do a cut attack, only available with bladed weapons
	int *crush;				//do a crush attack, only with blunt weapons
	int *stab;				//do a stab attack, only pointed weapons
	int *parry;				//
	int *feint;				//
	int *dodgeMod;			//
	int *retreatMod;		//
	int *grappleMod;		//corresponding form number will be NULL if no grapple
};

#endif
